### ISSUE TITLE
Yaml Exception when opening the RawEditor

### ISSUE THREAD

**Issue by svendroid** [pkozul/lovelace-floorplan#19]
I added the floorplan-card by using the RawEditor in the Lovelace UI. The card is displayed corretly but when reopening the RawEditor the editor is blank and I get following error in the Browser console:

```
Uncaught (in promise) 
i {name: "YAMLException", reason: "unacceptable kind of an object to dump [object SVGSVGElement]", mark: undefined, message: "unacceptable kind of an object to dump [object SVGSVGElement]", stack: "YAMLException: unacceptable kind of an object to d…cal:8123/frontend_latest/app.911ad0e2.js:2:47066)"}
name: "YAMLException"
reason: "unacceptable kind of an object to dump [object SVGSVGElement]"
mark: undefined
message: "unacceptable kind of an object to dump [object SVGSVGElement]"
stack: "YAMLException: unacceptable kind of an object to dump [object SVGSVGElement]↵    at Z (http://hassio.local:8123/frontend_latest/chunk.543b2c7f6922940a8a31.js:2733:193326)↵    at http://hassio.local:8123/frontend_latest/chunk.543b2c7f6922940a8a31.js:2733:192224↵    at Z (http://hassio.local:8123/frontend_latest/chunk.543b2c7f6922940a8a31.js:2733:192328)↵    at http://hassio.local:8123/frontend_latest/chunk.543b2c7f6922940a8a31.js:2733:192224↵    at Z (http://hassio.local:8123/frontend_latest/chunk.543b2c7f6922940a8a31.js:2733:192328)↵    at ee (http://hassio.local:8123/frontend_latest/chunk.543b2c7f6922940a8a31.js:2733:193917)↵    at e.exports.safeDump (http://hassio.local:8123/frontend_latest/chunk.543b2c7f6922940a8a31.js:2733:194005)↵    at HTMLElement.value (http://hassio.local:8123/frontend_latest/chunk.232e8e3f43c56c6be54c.js:100:21607)↵    at b.commit (http://hassio.local:8123/frontend_latest/app.911ad0e2.js:2:49781)↵    at m.commit (http://hassio.local:8123/frontend_latest/app.911ad0e2.js:2:47066)"
__proto__: Error
```

The `.storage/lovelace` entries for the card looks like this:
```
...
{
  "cards": [
    {
      "config": {
        "debug": true,
        "image": "/local/floorplan/wohnzimmer/floorplan.svg?v=1.1.14",
        "log_level": "debug",
        "rules": [
          {
            "entities": [
              "binary_sensor.main_bedroom",
              "binary_sensor.living_area",
              "binary_sensor.double_garage"
            ],
            "states": [
              {
                "class": "binary-sensor-off",
                "state": "off"
              },
              {
                "class": "binary-sensor-on",
                "state": "on"
              }
            ]
          }
        ],
        "stylesheet": "/local/floorplan/wohnzimmer/floorplan.css?v=1.1.14"
      },
      "title": "Simple Floorplan",
      "type": "custom:floorplan-card"
    }
  ],
  "icon": "mdi:floor-plan",
  "path": "floorplan",
  "title": "Floorplan"
}
...
```

It seems like the dumper.js cannot dump a SVGElement. Does somebody know how to fix this? Or give me a direction?

**Comment by svendroid** [comment]
When I delete the image property the RawEditor can be opened again. 
When I then readd the image the Error occurs again.

**Comment by JazekerXX** [comment]
when i open the raw editor i see also a blank screen. i have found a workaround though, if you go to another view/page and press f5, open the raw editor on the other view and it's showing the normal code again. so maybe it's a little bug..

**Comment by svendroid** [comment]
@JazekerXX the workarround works for me too. Thanks for the tip.

**Comment by JazekerXX** [comment]
> @JazekerXX the workarround works for me too. Thanks for the tip.

Nice! Glad i could help..

**Comment by welnaaa** [comment]
I have also the same issue, was figting with it whole day ...
 thanks for the tip with workaround ;>

**Comment by JazekerXX** [comment]
> I have also the same issue, was fighting with it whole day ...
> thanks for the tip with workaround ;>

you're welcome :)

**Comment by exetico** [comment]
Hi all,

I've updated the documentation. I hope this works as it should. If now, let me know - and I'll repoen it :-)
